#!/bin/bash

BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH, BRANCH=$BRANCH"

if [[ "$BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "true" ]]
then
  echo "********** BUILD DEV **********"
  bundle exec fastlane build_dev
elif [[ "$BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "true" ]]
then
  echo "********** BUILD PRE-PROD **********"
  bundle exec fastlane build_pre_prod_enterprise
elif [[ "$BRANCH" == "release"* ]]
then
  echo "********** BUILD PROD **********"
  bundle exec fastlane build_prod_enterprise
else
  echo "NOTHING"
fi